/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softecon.javaswing.test.forms;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import softecon.javaswing.test.utils.Tools;
import softecon.javaswing.test.vo.VO_Employee;
import softecon.javaswing.test.vo.VO_Job;

/**
 *
 * @author tkol
 */
public class AddNewEmployeeForm extends javax.swing.JDialog {
    
    ArrayList<VO_Job> jobList;
    ArrayList<VO_Employee> empList;

    /**
     * Creates new form AddNewEmployeeForm
     */
    public AddNewEmployeeForm() {
        setModal(true);
        initComponents();
        init();
//        ImageIcon img = new ImageIcon("C:\\Users\\tkol.SOFTECON\\Documents\\NetBeansProjects\\JavaSwing\\src\\softecon\\javaswing\\test\\icons/logo.png");
//        this.setIconImage(img.getImage());
        
    }
    
    public void init(){
         Tools.setFrameIcon(this);
        
        jobList = new ArrayList<VO_Job>();
        empList = new ArrayList<VO_Employee>();
        populateList();
        String [] jobsArray = new String[jobList.size()];
        for(int i = 0; i <jobList.size(); i++){
            jobsArray[i] = jobList.get(i).getNameOfJob() + " with avg salary of :"+jobList.get(i).getSalary();
        }
        empJobCb.setModel(new javax.swing.DefaultComboBoxModel<>(jobsArray));
    }
    
     public void saveEmpToFile(){
        try {
            FileOutputStream fileOutputStream = new FileOutputStream("Employees.dat");
            ObjectOutputStream outputFile = new ObjectOutputStream(fileOutputStream);

               for(VO_Employee emp : empList){
                   outputFile.writeObject(emp);
               }
               outputFile.close();
               JOptionPane.showMessageDialog(null, "You did it!");
               this.dispose();
        } catch (IOException e) {
            JOptionPane.showConfirmDialog(null, e.getMessage(), "Something's wrong... '3'", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void populateList(){
        // try to populate the arraylist of jobs just like i did in addNewFormJob
        //it starts here and ends....
       try{
           FileInputStream file = new FileInputStream("Jobs.dat");
        ObjectInputStream inputFile = new ObjectInputStream(file);
        
        boolean endOfFile = false;
        
        while(!endOfFile){
            try {
                jobList.add((VO_Job)inputFile.readObject());
                
            } catch (EOFException e) {
//                JOptionPane.showMessageDialog(null, e.getMessage(), "END OF FILE", JOptionPane.INFORMATION_MESSAGE);
                endOfFile = true;
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Something's wrong... '1'", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        inputFile.close();
       }catch(IOException ex){
           JOptionPane.showMessageDialog(null, ex.getMessage(), "Something's wrong... '2'", JOptionPane.ERROR_MESSAGE);
       }
       //ends here the population of the joblist, the arraylist
       //------------------------------------------------------
       //i do the same to populate the emplist, the arraylist of employees
       try{
           FileInputStream file2 = new FileInputStream("Employees.dat");
           ObjectInputStream inputFile2 = new ObjectInputStream(file2);
        
        boolean endOfFile = false;
        
        while(!endOfFile){
            try {
                empList.add((VO_Employee)inputFile2.readObject());
                
            } catch (EOFException e) {
//                JOptionPane.showMessageDialog(null, e.getMessage(), "END OF FILE", JOptionPane.INFORMATION_MESSAGE);
                endOfFile = true;
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Something's wrong... '1'", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        inputFile2.close();
       }catch(IOException ex){
           JOptionPane.showMessageDialog(null, ex.getMessage(), "Something's wrong... '2'", JOptionPane.ERROR_MESSAGE);
       }
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        empIdTxt = new javax.swing.JTextField();
        empNameTxt = new javax.swing.JTextField();
        empSurnameTxt = new javax.swing.JTextField();
        empSaveBtn = new javax.swing.JButton();
        empJobCb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Employee");
        setMaximumSize(new java.awt.Dimension(770, 450));
        setMinimumSize(new java.awt.Dimension(770, 450));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel1.setText("Add a new Employee");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel2.setText("Employee ID :");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel3.setText("Employee Name :");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel4.setText("Employee Surname :");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel5.setText("Choose Job :");

        empIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIdTxtActionPerformed(evt);
            }
        });

        empSaveBtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        empSaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softecon/javaswing/test/icons/save.png"))); // NOI18N
        empSaveBtn.setText("SAVE");
        empSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSaveBtnActionPerformed(evt);
            }
        });

        empJobCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(233, 233, 233))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empIdTxt)
                            .addComponent(empNameTxt)
                            .addComponent(empSurnameTxt)
                            .addComponent(empJobCb, 0, 302, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(empSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(empIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(empNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(empSurnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(empJobCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(empSaveBtn)
                .addGap(63, 63, 63))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void empIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIdTxtActionPerformed

    //save button in addnewEmployeeForm
    //something happens when we [press the save button
    private void empSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSaveBtnActionPerformed
            try {
            Integer.parseInt( empIdTxt.getText().trim() );
            int id = Integer.parseInt(empIdTxt.getText().trim());
            String name = empNameTxt.getText().trim();
            String surname = empSurnameTxt.getText().trim();
            int job = empJobCb.getSelectedIndex();
            VO_Job finalJob = jobList.get(job);
            VO_Employee emp = new VO_Employee(id, name, surname, finalJob);
            empList.add(emp);
            saveEmpToFile();
            
        } catch (NumberFormatException  e) {
            JOptionPane.showMessageDialog(null, "please enter a valid number as an id");
            empIdTxt.setText("");
        }
            
            new AddNewEmployeeForm().setVisible(true);
    }//GEN-LAST:event_empSaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewEmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empIdTxt;
    private javax.swing.JComboBox<String> empJobCb;
    private javax.swing.JTextField empNameTxt;
    private javax.swing.JButton empSaveBtn;
    private javax.swing.JTextField empSurnameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
