/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softecon.javaswing.test.forms;


import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import softecon.javaswing.test.utils.Tools;
import static softecon.javaswing.test.utils.Tools.CurrentLookAndFell;
import softecon.javaswing.test.vo.VO_Employee;
import softecon.javaswing.test.vo.VO_GUI;
import softecon.javaswing.test.vo.VO_Job;

/**
 *
 * @author tkol
 */
public class MainForm extends javax.swing.JFrame {

    ArrayList<VO_Employee> empList;
    ArrayList<VO_Job> jobList;
    
    
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
//        Tools.setLookAndFell();
         initComponents(); 
         init();
     
        

    }
    
   public void init(){
       Tools.setFrameIcon(this);
        
        cb_GUIs.removeAllItems();
        Tools.populateComboBox(cb_GUIs);
        
        empList = new ArrayList<VO_Employee>();
        jobList = new ArrayList<VO_Job>();
        
        populateList();
   }
    
    
    
    public void populateList(){
        // try to populate the arraylist of jobs just like i did in addNewFormJob
        //it starts here and ends....
       try{
           FileInputStream file = new FileInputStream("Jobs.dat");
        ObjectInputStream inputFile = new ObjectInputStream(file);
        
        boolean endOfFile = false;
        
        while(!endOfFile){
            try {
                jobList.add((VO_Job)inputFile.readObject());
                
            } catch (EOFException e) {
//                JOptionPane.showMessageDialog(null, e.getMessage(), "END OF FILE", JOptionPane.INFORMATION_MESSAGE);
                endOfFile = true;
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Something's wrong... '1'", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        inputFile.close();
       }catch(IOException ex){
           JOptionPane.showMessageDialog(null, ex.getMessage(), "Something's wrong... '2'", JOptionPane.ERROR_MESSAGE);
       }
       //ends here the population of the joblist, the arraylist
       //------------------------------------------------------
       //i do the same to populate the emplist, the arraylist of employees
       try{
           FileInputStream file2 = new FileInputStream("Employees.dat");
           ObjectInputStream inputFile2 = new ObjectInputStream(file2);
        
        boolean endOfFile = false;
        
        while(!endOfFile){
            try {
                empList.add((VO_Employee)inputFile2.readObject());
                
            } catch (EOFException e) {
//                JOptionPane.showMessageDialog(null, e.getMessage(), "END OF FILE", JOptionPane.INFORMATION_MESSAGE);
                endOfFile = true;
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Something's wrong... '1'", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        inputFile2.close();
       }catch(IOException ex){
           JOptionPane.showMessageDialog(null, ex.getMessage(), "Something's wrong... '2'", JOptionPane.ERROR_MESSAGE);
       }
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        cb_GUIs = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbThemes = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileButton = new javax.swing.JMenu();
        exitButton = new javax.swing.JMenuItem();
        addButton = new javax.swing.JMenu();
        addEmpButton = new javax.swing.JMenuItem();
        addJobButton = new javax.swing.JMenuItem();
        editButton = new javax.swing.JMenu();
        editEmpButton = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Softecon Enterprise");
        setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        setMinimumSize(new java.awt.Dimension(770, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softecon/javaswing/test/icons/cropped-softecon-website-logo.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softecon/javaswing/test/icons/Gold-Partner-oracle.png"))); // NOI18N

        cb_GUIs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_GUIs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_GUIsActionPerformed(evt);
            }
        });

        jLabel3.setText("Themes");

        cbThemes.setText("JTattoo");
        cbThemes.setFocusable(false);
        cbThemes.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cbThemes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        cbThemes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbThemesActionPerformed(evt);
            }
        });

        fileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softecon/javaswing/test/icons/folder.png"))); // NOI18N
        fileButton.setText("File");
        fileButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N

        exitButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softecon/javaswing/test/icons/exit.png"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        fileButton.add(exitButton);

        jMenuBar1.add(fileButton);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softecon/javaswing/test/icons/add.png"))); // NOI18N
        addButton.setText("Add");
        addButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N

        addEmpButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        addEmpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softecon/javaswing/test/icons/addemployee.png"))); // NOI18N
        addEmpButton.setText("Add Employee");
        addEmpButton.setToolTipText("");
        addEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpButtonActionPerformed(evt);
            }
        });
        addButton.add(addEmpButton);

        addJobButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        addJobButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softecon/javaswing/test/icons/job.png"))); // NOI18N
        addJobButton.setText("Add Job");
        addJobButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJobButtonActionPerformed(evt);
            }
        });
        addButton.add(addJobButton);

        jMenuBar1.add(addButton);

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softecon/javaswing/test/icons/edit.png"))); // NOI18N
        editButton.setText("Edit");
        editButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N

        editEmpButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        editEmpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softecon/javaswing/test/icons/edit.png"))); // NOI18N
        editEmpButton.setText("Edit Employee");
        editEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmpButtonActionPerformed(evt);
            }
        });
        editButton.add(editEmpButton);

        jMenuBar1.add(editButton);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softecon/javaswing/test/icons/searchh.png"))); // NOI18N
        jMenu1.setText("View");
        jMenu1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softecon/javaswing/test/icons/searchh.png"))); // NOI18N
        jMenuItem1.setText("Show All Employees");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbThemes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_GUIs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_GUIs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(cbThemes)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //---- EDIT EMPLOYEE BUTTON ----//
    //---- EDIT BUTTON AT MAIN FORM ----//
    private void addEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpButtonActionPerformed
        new AddNewEmployeeForm().setVisible(true);
    }//GEN-LAST:event_addEmpButtonActionPerformed

    //--- EXIT BUTTON ------
    //the exit button
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
//            System.exit(0);
        int confirmed = JOptionPane.showConfirmDialog(null,"Are you sure you want to exit the program?", "Exit Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
          dispose();
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void addJobButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJobButtonActionPerformed
        new AddNewJobForm().setVisible(true);
    }//GEN-LAST:event_addJobButtonActionPerformed

    private void editEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmpButtonActionPerformed
        try {
//            if(empList.isEmpty()){
//           JOptionPane.showMessageDialog(null, "There are no employees in your files to modify");       
        new EditEmployeeForm().setVisible(true);

       }catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "There are no employees in your files to modify");
//            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
    }//GEN-LAST:event_editEmpButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new ShowAllEmployees().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cb_GUIsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_GUIsActionPerformed
        if(cbThemes.isSelected()){
            int selectedIndex = cb_GUIs.getSelectedIndex();
            switch(selectedIndex){
                case 0:
            {
                try {
                    UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
                    SwingUtilities.updateComponentTreeUI(this);
                    this.pack();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                    
                    break;
                case 1:
                    try {
                    UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                    SwingUtilities.updateComponentTreeUI(this);
                    this.pack();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                    break;
                case 2:
                    try {
                    UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
                    SwingUtilities.updateComponentTreeUI(this);
                    this.pack();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                    break;
                case 3:
                    try {
                    UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
                    SwingUtilities.updateComponentTreeUI(this);
                    this.pack();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                    break;
                default :
                    break;
            }
        }else{
            try {
            if(cb_GUIs.getItemCount()<=0) return;
            
            int selectedIndex = cb_GUIs.getSelectedIndex();
            String selectedClassName = ((VO_GUI)cb_GUIs.getSelectedItem()).getClassName();
//            System.out.println(selectedIndex+".  "+selectedClassName);
             
            UIManager.setLookAndFeel(selectedClassName);
            //these 2 lines will change the look and feel at run time
            //update the component with the new Look and feel
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
    }//GEN-LAST:event_cb_GUIsActionPerformed

    private void cbThemesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbThemesActionPerformed
        
        if(cbThemes.isSelected()){
            cb_GUIs.removeAllItems();
            cb_GUIs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dark Noir", "Arcy", "Texture", "Smart" }));
            
        }else{
            cb_GUIs.removeAllItems();
            Tools.populateComboBox(cb_GUIs);
        }
            
    }//GEN-LAST:event_cbThemesActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu addButton;
    private javax.swing.JMenuItem addEmpButton;
    private javax.swing.JMenuItem addJobButton;
    private javax.swing.JCheckBox cbThemes;
    private javax.swing.JComboBox<String> cb_GUIs;
    private javax.swing.JMenu editButton;
    private javax.swing.JMenuItem editEmpButton;
    private javax.swing.JMenuItem exitButton;
    private javax.swing.JMenu fileButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
